Feature/a b graph [ PART 2 ]
TheInteract/Apollo pull request #14
Opened 2017-04-23 19:19 UTC by pNagi

2017-04-23 21:30 UTC, chinclubi commented
**ISSUE**
Each node in Apollo client state was differentiated by `_id`  and `_id` of nodeType was resolved by `actionTypeId` which is same of each version. 

**WHAT'S HAPPENING?**
1. Feature version `A` fetched a data from server including `nodes` which `_id` is an `actionTypeId`
2. Apollo set a new state by using recieved data.
3. Feature version `B` fetched a data from server including `nodes` which `_id` is an `actionTypeId`, same as feature version `A`.
4. Apollo overwrite a client state by using a recived node from server which same `_id`

It's mean, feature `A` and feature `B` are using same store.

**SUGGESTION**
Resolve `_id` of node by using a unique `_id` for each version. 

Example, `_id` = `actionTypeId + version.name`

**ResolveHelper.js** - pass `inputVersion` to each node
```javascript
export const generateNodes = (sessions = [], inputVersion) => _.flow([
  sessions => _.filter(sessions, filterByVersion(inputVersion)),
  sessions => _.map(sessions, mapSessionToNodes),
  nodes => _.flattenDeep(nodes),
  nodes => _.groupBy(nodes, node => node.actionTypeId),
  nodes => _.map(nodes, node => ({ ...node[0], count: node.length, inputVersion }))
])(sessions)
...
...
...
export const mapActionsToLinks = inputVersion => session => {
  const actions = removeFocusAndBlur(session.actions)
  const links = []

  if (actions.length > 1) {
    for (let i = 0; i < actions.length - 1; i++) {
      links.push({
        source: `${actions[i].actionTypeId}.${inputVersion.name}`,
        target: `${actions[i + 1].actionTypeId}.${inputVersion.name}`
      })
    }
  }
...
...
...
export const generateLinks = (sessions = [], inputVersion) => _.flow([
  sessions => _.filter(sessions, filterByVersion(inputVersion)),
  sessions => _.map(sessions, mapActionsToLinks(inputVersion)),
  links => _.flattenDeep(links),
  links => _.groupBy(links, link => link.source + link.target),
  links => _.map(links, link => ({ ...link[0], count: link.length, inputVersion })),
])(sessions)
...
...
...
export const generatePaths = (sessions = [], inputVersion) => _.flow([
  sessions => _.filter(sessions, filterByVersion(inputVersion)),
  sessions => _.map(sessions, mapSessionsToPaths),
  paths => _.groupBy(paths, reduceActionTypeIds),
  paths => _.map(paths, path => ({ ...path[0], count: path.length, inputVersion })),
])(sessions)
```

**PathType.js** - add `inputVersion` to each `action`
```javascript
const PathType = new GraphQLObjectType({
  name: 'Path',
  description: 'Path type',
  fields: () => ({
    _id: { type: new GraphQLNonNull(GraphQLString) },
    nodes: {
      type: new GraphQLList(NodeType),
      resolve: ({ actions, inputVersion }) => (
        _.map(actions, action => ({ ...action, inputVersion }))
      )
    },
    count: { type: new GraphQLNonNull(GraphQLInt) },
  })
```

**NodeType.js** - field `_id` should resolve with `actionTypeId` and `inputVersion.name`
```javascript
const NodeType = new GraphQLObjectType({
  name: 'Node',
  description: 'Node type',
  fields: () => ({
    _id: {
      type: new GraphQLNonNull(GraphQLString),
      resolve: root => (
        `${root.actionTypeId}.${root.inputVersion.name}`
      )
    },
    type: { type: new GraphQLNonNull(GraphQLString) },
    data: {
      type: new GraphQLNonNull(GraphQLString),
      resolve: root => root.url || removeInteractClick(root.target) || root.endpoint
    },
    count: { type: GraphQLInt },
  })
})
```

2017-04-24 17:49 UTC, 0xchimz requested changes

2017-04-24 17:49 UTC, chinclubi commented on src/shared/nt-core/MainPage.styl
> +  // box-shadow 1px 0 5px 0 rgba(c-gray900, 0.5)
remove a comment before merging with a master branch?

2017-04-24 17:49 UTC, chinclubi commented on src/shared/nt-core/MainPage.styl
> +  // background-color c-gray25
remove a comment?

2017-04-24 17:49 UTC, chinclubi commented on src/shared/nt-results/ResultsByLoadContainer.react.js
> +        ? this.container.clientWidth : x
Is this better?
```javascript
this.setState({
  x: (x < 0) ? 0 : (
    x > this.container.clientWidth ? (
      this.container.clientWidth
    ) : x
  )
})
```

2017-04-24 17:49 UTC, chinclubi commented on src/shared/nt-results/ResultsPage.react.js
>    }
```javascript
handleSelectFeature = selectedFeatureId => () => {
    this.setState({ selectedFeatureId })
}
```

2017-04-24 17:49 UTC, chinclubi commented on src/shared/nt-results/ResultsPage.react.js
> +              key={feature._id}
Should be `Link` or add cursor `pointer` to nt__link?

2017-04-24 17:49 UTC, chinclubi commented on src/shared/nt-results/ResultsPage.styl
>      transition background-color 0.1s ease color 0.1s ease
Add `cursor: pointer;` ?

2017-04-24 17:59 UTC, pNagi commented on src/shared/nt-results/ResultsByLoadContainer.react.js
> +        ? this.container.clientWidth : x
I don't think so, but I didn't mean what I write is good. Gonna look for better way to write this.

2017-04-24 18:00 UTC, pNagi commented on src/shared/nt-results/ResultsPage.react.js
>    }
The `featureId` receive from params is not **selected** yet. It is **going to be selected**.

2017-04-24 18:13 UTC, 0xchimz requested changes

2017-04-24 18:13 UTC, chinclubi commented on src/shared/nt-results/ResultsPage.react.js
> +            this.renderLink(url.parse(sessionType.url).path, '', `/${sessionType._id}`)
if more than one argument of a method can be empty or null, you should pass arguments with an object type.

For example.
```javascript 
renderLink = (content, { iconName, path = '' }) => (
    <NavLink
      key={path}
      to={`${this.props.match.url}${path}`}
      activeClassName={styles.nt__activeLink}
      exact
    >
      <div className={styles.nt__link}>
        { iconName && <i className={`fa fa-${iconName}`} aria-hidden='true' />}
        <span>{content}</span>
      </div>
    </NavLink>
  )
....
...
...
this.renderLink('setting', { iconName: 'cog' })
....
this.renderLink(url.parse(sessionType.url).path, { path: `/${sessionType._id}` })
```

VSCode also have a guide when calling a method.
![image](https://cloud.githubusercontent.com/assets/5950717/25351916/5e7673f6-2954-11e7-8e41-2ec0498c5c67.png)

2017-04-24 18:27 UTC, pNagi commented on src/shared/nt-results/ResultsPage.react.js
> +            this.renderLink(url.parse(sessionType.url).path, '', `/${sessionType._id}`)
Right now this method is duplicate and need to be refactored in the future, so this problem will be gone with the refactoring. Anyways, I'm not sure if it still have time to do this.

2017-04-24 18:34 UTC, chinclubi commented on src/shared/nt-results/ResultsPage.react.js
> +            this.renderLink(url.parse(sessionType.url).path, '', `/${sessionType._id}`)
ok, both of them should be coded according to the suggestion above.

2017-04-24 18:38 UTC, chinclubi commented
![image](https://cloud.githubusercontent.com/assets/5950717/25352874/a691e118-2957-11e7-8506-3fdae74ad713.png)
I can't recognize this to be a button. I suggest adding a border or shadow.

2017-04-24 18:49 UTC, 0xchimz approved these changes

2017-04-24 18:52 UTC, merged