:sparkles: bring back the overall graph
TheInteract/Apollo pull request #15
Opened 2017-04-24 19:39 UTC by pNagi

2017-04-24 20:41 UTC, 0xchimz requested changes

2017-04-24 20:41 UTC, chinclubi commented on src/shared/nt-results/ResultsByLoadContainer.react.js
> +    />,
- The divider should assign to `this.divider`.
- `renderABGraphs` return an array without unique `key` of each element.

2017-04-25 05:48 UTC, chinclubi commented on src/shared/nt-results/ResultsByLoadContainer.react.js
> +        <Loading key='loading' />
key is not unique.
what's about `key='loading-${graph}'`?

2017-04-25 05:52 UTC, 0xchimz approved these changes

2017-04-25 05:57 UTC, 0xchimz requested changes

2017-04-25 05:57 UTC, chinclubi commented on src/shared/nt-results/ResultsByLoadContainer.react.js
> +    <div className={styles[styleName]} style={style}>
`key`

2017-04-25 06:10 UTC, 0xchimz requested changes

2017-04-25 06:10 UTC, chinclubi commented on src/shared/nt-results/ResultsByLoadContainer.react.js
> +      onClick={() => { console.log('click') }}
remove `console.log`

2017-04-25 06:13 UTC, 0xchimz approved these changes

2017-04-25 06:22 UTC, merged