Feature/subscribe feature change
TheInteract/Apollo pull request #8
Opened 2017-04-18 08:44 UTC by chinclubi

- update apollo store with `_id`
- create subscribe for feature change
- add loading and disable to submit button

2017-04-18 10:01 UTC, pNagi requested changes

2017-04-18 10:01 UTC, pNagi commented on src/server/graphql/MutationRootType.js
> +      }
```js
const featureUpdated = await Collections.update(...code...).value
pubsub.publish('featureUpdated', featureUpdated)
return featureUpdated
```

or

```js
const result = await Collections.update(...code...)
pubsub.publish('featureUpdated', result.value)
return result.value
```

2017-04-18 10:01 UTC, pNagi commented on src/server/graphql/MutationRootType.js
> +        pubsub.publish('featureChanged', updatedFeature.value)
```js
pubsub.publish('featureUpdated', featureUpdated)
```

or

```js
pubsub.publish('featureUpdated', result.value)
```

2017-04-18 10:01 UTC, pNagi commented on src/server/graphql/SubscriptionRootType.js
> +    featureChanged: {
`featureUpdated`

2017-04-18 10:01 UTC, pNagi commented on src/server/mongodb/commands/Update.js
> +  db.collection(collectionName).findOneAndUpdate(query, update, { returnOriginal: false })
I think this line is too long.

```js
 db.collection(collectionName).findOneAndUpdate(query, update, {
  returnOriginal: false
})
```

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/CreateFeatureForm.react.js
> +    this.state = Object.assign({}, initialState)
I don't like `Object.assign()`

how about `{ ...initialState }`

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/CreateFeatureForm.react.js
> +    e.preventDefault()
Why `e.preventDefault()` before mutate`? (Really don't know if the order matter)

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/CreateFeatureForm.react.js
> +          this.setState(Object.assign({}, initialState))
Same as above comment.

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/CreateFeatureForm.react.js
> +            }
```js
className={classNames({
  [styles['--loading']]: this.state.loading
})}
```

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/CreateFeatureForm.styl
> +        animation spinAround $l-spin-time infinite linear
duplicate css

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/FeaturesPage.react.js
> +const FEATURE_CHANGED_SUBSCRIPTION = gql`
`FEATURE_UPDATED_SUBSCRIPTION`

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/FeaturesPage.react.js
> +  subscription onFeatureChanged ($productId: String!) {
`onFeatureUpdated`

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/FeaturesPage.react.js
> +    featureChanged (productId: $productId) {
`featureUpdated`

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/FeaturesPage.react.js
> +      document: FEATURE_ADDED_SUBSCRIPTION,
`FEATURE_UPDATED_SUBSCRIPTION`

2017-04-18 10:01 UTC, pNagi commented on src/shared/nt-features/FeaturesPage.react.js
> +        return update(prev, { features: { [index]: { active: { $set: updatedFeature.active } } } })
I think this line is too long.

2017-04-18 11:10 UTC, chinclubi commented on src/shared/nt-features/CreateFeatureForm.react.js
> +    e.preventDefault()
order is matter. if there is sync function before `e.preventDefault()`, events will run a code before canceling them.

2017-04-18 17:52 UTC, pNagi requested changes

2017-04-18 17:52 UTC, pNagi commented on src/shared/nt-features/CreateFeatureForm.react.js
> +import LoadingComponent from '../nt-uikit/Loading.react'
```js
import { Loading } from '../nt-uikit'
```

2017-04-18 17:52 UTC, pNagi commented on src/shared/nt-features/CreateFeatureForm.react.js
> +            <LoadingComponent
`<Loading`

2017-04-18 17:52 UTC, pNagi commented on src/shared/nt-features/FeaturesPage.react.js
> +        const updatedFeature = subscriptionData.data.featureChanged
`featureUpdated`

2017-04-18 17:52 UTC, pNagi commented on webpack.config.prod.babel.js
> +  // ],
please remove comments

2017-04-19 09:17 UTC, pNagi approved these changes

2017-04-19 09:17 UTC, merged